[tool.bandit]
skips = ["B101"]

[tool.black]
line-length = 80

[tool.autopep8]
max_line_length = 80
ignore = "E266"
in-place = true
recursive = true
aggressive = 3

[tool.pytest.ini_options]
testpaths = [
    "tests",
    "pyben",
]
console_output_style = "progress"
addopts = "--maxfail=5"

[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
