name: CI

on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest toml pylint pycodestyle pydocstyle
          pip install pytest-cov pytest-pylint pytest-randomly
          pytest --cov=tests --cov=pyben --pylint tests
          pycodestyle pyben tests
          pydocstyle pyben tests

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest tests
          coverage report
          coverage xml -o coverage.xml

      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@4.0.0

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
